services:
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Password@1
      - ACCEPT_EULA=1
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
volumes:
  redis-data:
  sql-data: