services:
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Password@1
      - ACCEPT_EULA=1
    ports:
      - "1433:1433"

